({
    baseUrl: ".",
    mainConfigFile:"main.js",
    name: "main",
    out: "admin.bunddle.js",
    preserveLicenseComments:false,
    optimize:'none',
    paths: {
    requiredlib:'../libs/require/require',
    bootstrap: '../../assets/bootstrap/js/bootstrap.bundle.min',
    jquery: '../libs/jquery/jquery-min',
    underscore: '../libs/underscore/underscore-min',
    backbone: '../libs/backbone/backbone-min',
    jqueryCookie: '../../assets/jquery.cookies/jquerycookie',
    bootstrapSlider: '../../assets/range_slider/bootstrap-slider',
    magnificPopup: '../../assets/magnific-popup/jquery.magnific-popup-min',
    locationpicker: '../../assets/map/locationpicker',
    fastclick: 'fastclick/lib/fastclick',
    datepickerBT: '../../assets/datepicker/dist/js/bootstrap-datepicker',
    timepicker: '../../assets/timepicker/timepicker',
    hotkeys: '../../assets/bootstrapWysiwyg/jquery.hotkeys',
    wysiwyg: '../../assets/bootstrapWysiwyg/bootstrap-wysiwyg',
    tagmanager: '../../assets/tagmanager/tagmanager.min',
    typeahead: '../../assets/tagmanager/bootstrap3-typeahead.min',
    flot: '../../assets/Flot/jquery.flot',
    curvedLines: '../../assets/flot.curvedlines/curvedLines',
    validate: '../../assets/jquery.validate/jquery.validate.min',
    inputmask: '../../assets/inputMask/jquery.inputmask.bundle',
    icheck: '../../assets/iCheck/icheck.min',
    select2: '../../assets/select2/js/select2.full.min',
    moment: '../../assets/datepicker/moment.min',
    jqueryUI: '../../assets/jquery-ui/jquery-ui.min',
    plugin: '../../plugin',
    slim: '../../assets/slim/slim.jquery.min',
    multiselect: '../../assets/multiselect/js/multiselect.min',
    RealTimeUpload: '../../assets/realTimeUpload/js/RealTimeUpload',
    Waves: '../../assets/theme-setup/plugins/node-waves/waves.min',
    adminjs: '../../assets/theme-setup/js/admin',
    jqueryNestable: '../../assets/jquery-nestable/jquery.nestable',
    custom: 'custom',
    xlsx: '../../assets/SheetJS/xlsx.full.min',
    xlsprocess: '../../assets/SheetJS/xlsProcess',
    minicolors: '../../assets/Color-Picker/jquery.minicolors',
    Quill: '../../assets/quill-1.3.6/quill.min',
    templateEditor: '../../assets/templateEditor/dragDrop',
    bootstrapSelect: '../../assets/bootstrap-select-1.13.14/dist/js/bootstrap-select.min',
    notify: '../../assets/theme-setup/plugins/bootstrap-notify/bootstrap-notify.min',
    fullcalendar: '../../assets/theme-setup/plugins/fullcalendar/fullcalendar.min',
    calender: '../../assets/bootstrap-calendar/calender/main',
    Swal: '../../assets/theme-setup/plugins/sweetalert/sweetalert2.min',
    jquery360: '../../assets/jquery-ui/jquery-ui.min',
    },
    include:'requiredlib'
})