define([
  'underscore',
  'backbone',
], function (_, Backbone) {

  var themeOptionModel = Backbone.Model.extend({
    idAttribute: "theme_option_id",
    defaults: {
      theme_option_id: 1,
      primary_color: null,
      secondary_color: null,
      font_family: null,
      user_signup: null,
      instant_signup: null,
      page_title_h1: null,
      custom_css: null,
      custom_js: null,
      body_font: {
        "fontFamily": null,
        "fontWeight": null,
        "color": null,
      },
      navigation_style_and_anchor: {
        "fontFamily": null,
        "fontWeight": null,
        "color": null,
      },
      heading_h1_style: {
        "fontFamily": null,
        "fontWeight": null,
        "color": null,
      },
      heading_h2_style: {
        "fontFamily": null,
        "fontWeight": null,
        "color": null,
      },
      heading_h3_style: {
        "fontFamily": null,
        "fontWeight": null,
        "color": null,
      },
      heading_h4_style: {
        "fontFamily": null,
        "fontWeight": null,
        "color": null,
      },
      heading_h5_style: {
        "fontFamily": null,
        "fontWeight": null,
        "color": null,
      },
      heading_h6_style: {
        "fontFamily": null,
        "fontWeight": null,
        "color": null,
      },
      para_and_small_elm: {
        "fontFamily": null,
        "fontWeight": null,
        "color": null,
      },
      show_strip_header: null,
      contact_no: null,
      email_id: null,
      office_address: null,
      office_timing: null,
      strip_header_background_color: null,
      strip_header_font_color: null,
      header_layout: null,
      fixed_header: null,
      fixed_header_in_inner_pages: null,
      header_background_color: null,
      header_background_color_inner_pages: null,
      header_text_and_border_color: null,
      header_text_layout: 'center',
      header_search: null,
      header_page_logo: null,
      page_banner_image:null,
      page_banner_color:null,
      logo_for_inner_pages: null,
      favicon: null,
      google_reCaptcha: null,
      footer_layout: null,
      select_footer_widget_layout: null,
      footer_top_area_background_color: null,
      footer_bottom_area_background_color: null,
      footer_top_text_color: null,
      footer_bottom_text_color: null,
      facebook_url: null,
      twitter_url: null,
      instagram_url: null,
      tumbler_url: null,
      youtube_url: null,
      linkdin_url: null,
      pinterest_url: null,
      vk_url: null,
      Swiggy: null,
      Zomato: null,
      social_header: 'n',
      social_footer: 'n',
      social_navbar: 'n',
      social_footer_strip: 'n',
      google_secret_key: null,
      google_client_key: null,
      footer_layout_one:{
        "footerLayoutOne_1" :null,
      },
      footer_layout_two: {
        "footerLayoutTwo_1" :null,
        "footerLayoutTwo_2" :null,
      },
      footer_layout_three: {
        "footerLayoutThree_1" :null,
        "footerLayoutThree_2" :null,
        "footerLayoutThree_3" :null,
      },
      footer_layout_four: {
        "footerLayoutFour_1" :null,
        "footerLayoutFour_2" :null,
        "footerLayoutFour_3" :null,
        "footerLayoutFour_4" :null,
      },
      show_footer_home: 'no',
      show_footer_inner_page: 'no',
      show_recent_blogs:'no',
      blog_limit: null,
      show_footer_strip :'no',
      footer_strip_text : null,
      show_header_strip_mobile:'Desktop',
      menu_text_transform:'no',
      logo_width:null,
      show_enquiry_form:'no',
      status: 'active',
    },
    urlRoot: function () {
      return APIPATH + 'themeOptionMaster/'
    },
    parse: function (response) {
      return response.data[0];
    }
  });
  return themeOptionModel;
});

